import type { Capability } from '@bvp/shared';

export const qwenT2ICapability: Capability = {
  id: 'qwen.t2i',
  displayName: 'Qwen 文生图',
  shortName: '文生图',
  category: 't2i',
  providerName: 'dashscope',
  sync: true,
  models: [
    { value: 'qwen-image-2.0-pro', label: 'Qwen Image 2.0 Pro', default: true, description: '最强能力，2.0 系列旗舰' },
    { value: 'qwen-image-2.0', label: 'Qwen Image 2.0', description: '速度与效果平衡' },
    { value: 'qwen-image-max', label: 'Qwen Image Max', description: '真实感最强' },
    { value: 'qwen-image-plus', label: 'Qwen Image Plus', description: '艺术风格' },
  ],
  promptSpec: { required: true, maxChars: 1300, supportsNegative: true },
  mediaSpec: { mode: 'none', slots: [] },
  batch: { nativeMax: 6, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 5, max: 20 },
  docPath: 'doc/qwen-t2i.md',
  description: '阿里云通义千问图像生成模型，支持中英文 prompt，最高 2048×2048。',
  parameterSpec: [
    {
      key: 'parameters.size',
      label: '分辨率',
      type: 'enum',
      default: '2048*2048',
      enum: [
        { value: '2048*2048', label: '2048×2048 (1:1)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '2688*1536', label: '2688×1536 (16:9)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1536*2688', label: '1536×2688 (9:16)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '2368*1728', label: '2368×1728 (4:3)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1728*2368', label: '1728×2368 (3:4)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1664*928', label: '1664×928 (16:9)', modelScope: ['qwen-image-max', 'qwen-image-plus'] },
        { value: '928*1664', label: '928×1664 (9:16)', modelScope: ['qwen-image-max', 'qwen-image-plus'] },
        { value: '1472*1104', label: '1472×1104 (4:3)', modelScope: ['qwen-image-max', 'qwen-image-plus'] },
        { value: '1104*1472', label: '1104×1472 (3:4)', modelScope: ['qwen-image-max', 'qwen-image-plus'] },
        { value: '1328*1328', label: '1328×1328 (1:1)', modelScope: ['qwen-image-max', 'qwen-image-plus'] },
      ],
      sweepable: { allowed: true, strategies: ['list'], costMultiplier: 'linear' },
      warn: '影响生成质量与计费',
    },
    {
      key: 'parameters.n',
      label: '生成张数',
      type: 'int',
      default: 1,
      range: [1, 6],
      step: 1,
      dependsOn: [{ field: 'modelVariant', op: 'in', value: ['qwen-image-2.0-pro', 'qwen-image-2.0'] }],
      sweepable: { allowed: false },
      help: 'Max / Plus 系列固定为 1',
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
      help: '相同 seed 可提升可复现性',
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true, strategies: ['list'] },
      help: '由模型自动优化 prompt',
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
  ],
};

const COMMON_RATIO_ENUM = [
  { value: '16:9', label: '16:9' },
  { value: '9:16', label: '9:16' },
  { value: '1:1', label: '1:1' },
  { value: '4:3', label: '4:3' },
  { value: '3:4', label: '3:4' },
];

const COMMON_RESOLUTION_ENUM = [
  { value: '720P', label: '720P' },
  { value: '1080P', label: '1080P' },
];

export const wan27T2VCapability: Capability = {
  id: 'wan2.7.t2v',
  displayName: 'Wan 2.7 文生视频',
  shortName: '文生视频',
  category: 't2v',
  providerName: 'dashscope',
  sync: false,
  models: [{ value: 'wan2.7-t2v-2026-04-25', label: 'Wan 2.7 T2V', default: true }],
  promptSpec: { required: true, maxChars: 5000, supportsNegative: true, syntaxHelp: '支持时间戳分镜语法' },
  mediaSpec: {
    mode: 'unified_media',
    slots: [
      {
        kind: 'driving_audio',
        required: false,
        min: 0,
        max: 1,
        accept: ['audio'],
        label: '配音 (可选)',
        hint: '2-30 秒, ≤15MB, wav/mp3。不传则自动生成背景音。',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.7-t2v.md',
  description: 'Wan 2.7 文本生成视频，支持多镜头与时间戳分镜，1080P/720P，时长 2-15 秒。',
  parameterSpec: [
    {
      key: 'parameters.resolution',
      label: '分辨率',
      type: 'enum',
      default: '1080P',
      enum: COMMON_RESOLUTION_ENUM,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
      warn: '直接影响计费',
    },
    {
      key: 'parameters.ratio',
      label: '宽高比',
      type: 'enum',
      default: '16:9',
      enum: COMMON_RATIO_ENUM,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.duration',
      label: '时长 (秒)',
      type: 'int',
      default: 5,
      range: [2, 15],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list', 'linearRange'] },
      warn: '按秒计费',
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const wan26I2VCapability: Capability = {
  id: 'wan2.6.i2v',
  displayName: 'Wan 2.6 图生视频',
  shortName: '图生视频 (2.6)',
  category: 'i2v',
  providerName: 'dashscope',
  sync: false,
  models: [
    { value: 'wan2.6-i2v-flash', label: 'Wan 2.6 I2V Flash', default: true, description: '快速版，可控有声/无声' },
    { value: 'wan2.6-i2v', label: 'Wan 2.6 I2V', description: '标准版' },
    { value: 'wan2.5-i2v-preview', label: 'Wan 2.5 I2V Preview' },
  ],
  promptSpec: { required: false, maxChars: 1500, supportsNegative: true },
  mediaSpec: {
    mode: 'single_image',
    slots: [
      {
        kind: 'first_frame',
        required: true,
        min: 1,
        max: 1,
        accept: ['image'],
        label: '首帧图',
        hint: 'JPEG/PNG/BMP/WEBP，240-8000 像素，≤20MB',
      },
      {
        kind: 'driving_audio',
        required: false,
        min: 0,
        max: 1,
        accept: ['audio'],
        label: '驱动音频 (可选)',
        hint: '2-30 秒, ≤15MB',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.6-i2v.md',
  description: 'Wan 2.6 首帧图生视频，支持单/多镜头、配音驱动、视频特效。',
  parameterSpec: [
    {
      key: 'parameters.resolution',
      label: '分辨率',
      type: 'enum',
      default: '1080P',
      enum: COMMON_RESOLUTION_ENUM,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.duration',
      label: '时长 (秒)',
      type: 'int',
      default: 5,
      range: [2, 15],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list', 'linearRange'] },
    },
    {
      key: 'parameters.shot_type',
      label: '镜头类型',
      type: 'enum',
      default: 'single',
      enum: [
        { value: 'single', label: '单镜头' },
        { value: 'multi', label: '多镜头' },
      ],
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.audio',
      label: '生成音频',
      type: 'bool',
      default: true,
      dependsOn: [{ field: 'modelVariant', op: 'eq', value: 'wan2.6-i2v-flash' }],
      sweepable: { allowed: false },
      help: '仅 Flash 模型支持有/无声切换',
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const wan27I2VCapability: Capability = {
  id: 'wan2.7.i2v',
  displayName: 'Wan 2.7 图生视频',
  shortName: '图生视频 (2.7)',
  category: 'i2v',
  providerName: 'dashscope',
  sync: false,
  models: [{ value: 'wan2.7-i2v-2026-04-25', label: 'Wan 2.7 I2V', default: true }],
  promptSpec: { required: true, maxChars: 5000, supportsNegative: true },
  mediaSpec: {
    mode: 'unified_media',
    slots: [
      {
        kind: 'first_frame',
        required: false,
        min: 0,
        max: 1,
        accept: ['image'],
        label: '首帧图',
        hint: 'JPEG/PNG/WEBP，独立或与尾帧/视频片段组合',
      },
      {
        kind: 'last_frame',
        required: false,
        min: 0,
        max: 1,
        accept: ['image'],
        label: '尾帧图 (可选)',
        hint: '与首帧一起使用以约束开始与结束',
      },
      {
        kind: 'first_clip',
        required: false,
        min: 0,
        max: 1,
        accept: ['video'],
        label: '视频续写片段',
        hint: '在此视频片段之后续写新内容',
      },
      {
        kind: 'driving_audio',
        required: false,
        min: 0,
        max: 1,
        accept: ['audio'],
        label: '驱动音频 (可选)',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.7-i2v.md',
  description: 'Wan 2.7 图生视频新协议：首帧 / 首尾帧 / 视频续写三合一。',
  parameterSpec: [
    {
      key: 'parameters.resolution',
      label: '分辨率',
      type: 'enum',
      default: '1080P',
      enum: COMMON_RESOLUTION_ENUM,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.duration',
      label: '时长 (秒)',
      type: 'int',
      default: 5,
      range: [2, 15],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list', 'linearRange'] },
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const wan26R2VCapability: Capability = {
  id: 'wan2.6.r2v',
  displayName: 'Wan 2.6 参考生视频',
  shortName: '参考生视频 (2.6)',
  category: 'r2v',
  providerName: 'dashscope',
  sync: false,
  models: [
    { value: 'wan2.6-r2v', label: 'Wan 2.6 R2V', default: true },
    { value: 'wan2.6-r2v-flash', label: 'Wan 2.6 R2V Flash', description: '快速版，可关音' },
  ],
  promptSpec: {
    required: true,
    maxChars: 1500,
    supportsNegative: true,
    referenceSyntax: 'character_n',
    syntaxHelp: '在 prompt 中使用 character1 / character2 ... 指代参考素材，按上传顺序排序',
  },
  mediaSpec: {
    mode: 'reference_urls',
    slots: [
      {
        kind: 'reference_image',
        required: false,
        min: 0,
        max: 5,
        accept: ['image'],
        label: '参考图像',
        hint: '0-5 张',
      },
      {
        kind: 'reference_video',
        required: false,
        min: 0,
        max: 3,
        accept: ['video'],
        label: '参考视频',
        hint: '0-3 段，图+视频总数 ≤5',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.6-r2v.md',
  description: 'Wan 2.6 参考生视频，最多 5 张参考图 / 3 段参考视频，用 characterN 在 prompt 中引用。',
  parameterSpec: [
    {
      key: 'parameters.size',
      label: '分辨率',
      type: 'enum',
      default: '1920*1080',
      enum: [
        { value: '1920*1080', label: '1920×1080 (1080P 16:9)' },
        { value: '1080*1920', label: '1080×1920 (1080P 9:16)' },
        { value: '1440*1080', label: '1440×1080 (1080P 4:3)' },
        { value: '1080*1440', label: '1080×1440 (1080P 3:4)' },
        { value: '1280*720', label: '1280×720 (720P 16:9)' },
        { value: '720*1280', label: '720×1280 (720P 9:16)' },
      ],
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.duration',
      label: '时长 (秒)',
      type: 'int',
      default: 5,
      range: [2, 10],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list', 'linearRange'] },
    },
    {
      key: 'parameters.shot_type',
      label: '镜头类型',
      type: 'enum',
      default: 'single',
      enum: [
        { value: 'single', label: '单镜头' },
        { value: 'multi', label: '多镜头' },
      ],
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.audio',
      label: '生成音频',
      type: 'bool',
      default: true,
      dependsOn: [{ field: 'modelVariant', op: 'eq', value: 'wan2.6-r2v-flash' }],
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const wan27R2VCapability: Capability = {
  id: 'wan2.7.r2v',
  displayName: 'Wan 2.7 参考生视频',
  shortName: '参考生视频 (2.7)',
  category: 'r2v',
  providerName: 'dashscope',
  sync: false,
  models: [{ value: 'wan2.7-r2v', label: 'Wan 2.7 R2V', default: true }],
  promptSpec: {
    required: true,
    maxChars: 5000,
    supportsNegative: true,
    referenceSyntax: 'image_n_video_n_zh',
    syntaxHelp: '在 prompt 中使用「图1 / 视频1」或英文「Image 1 / Video 1」指代参考素材',
  },
  mediaSpec: {
    mode: 'unified_media',
    slots: [
      {
        kind: 'reference_image',
        required: false,
        min: 0,
        max: 5,
        accept: ['image'],
        label: '参考图像',
        hint: '0-5 张，可与参考视频混用，总数 ≤5',
      },
      {
        kind: 'reference_video',
        required: false,
        min: 0,
        max: 3,
        accept: ['video'],
        label: '参考视频',
        hint: '0-3 段',
      },
      {
        kind: 'first_frame',
        required: false,
        min: 0,
        max: 1,
        accept: ['image'],
        label: '首帧约束 (可选)',
        hint: '提供则覆盖 ratio 参数',
      },
      {
        kind: 'reference_voice',
        required: false,
        min: 0,
        max: 1,
        accept: ['audio'],
        label: '音色参考 (可选)',
        hint: '1-10 秒, wav/mp3',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.7-r2v.md',
  description: 'Wan 2.7 参考生视频，多模态参考（图/视频/音色），支持首帧约束。',
  parameterSpec: [
    {
      key: 'parameters.resolution',
      label: '分辨率',
      type: 'enum',
      default: '1080P',
      enum: COMMON_RESOLUTION_ENUM,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.ratio',
      label: '宽高比',
      type: 'enum',
      default: '16:9',
      enum: COMMON_RATIO_ENUM,
      sweepable: { allowed: true, strategies: ['list'] },
      help: '含 first_frame 时此参数被忽略',
    },
    {
      key: 'parameters.duration',
      label: '时长 (秒)',
      type: 'int',
      default: 5,
      range: [2, 15],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list', 'linearRange'] },
      warn: '含参考视频时上限为 10 秒',
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const qwenImageEditCapability: Capability = {
  id: 'qwen.image_edit',
  displayName: 'Qwen 图片编辑',
  shortName: '图片编辑',
  category: 'i2i',
  providerName: 'dashscope',
  sync: true,
  models: [
    {
      value: 'qwen-image-2.0-pro',
      label: 'Qwen Image 2.0 Pro',
      default: true,
      description: 'Pro，文字/质感/语义最强',
    },
    { value: 'qwen-image-2.0', label: 'Qwen Image 2.0', description: '加速版，效果与速度平衡' },
    { value: 'qwen-image-edit-max', label: 'Qwen Image Edit Max', description: '工业设计/几何推理' },
    { value: 'qwen-image-edit-plus', label: 'Qwen Image Edit Plus', description: '支持多图融合' },
    { value: 'qwen-image-edit', label: 'Qwen Image Edit', description: '基础版，固定 1 张输出' },
  ],
  promptSpec: {
    required: true,
    maxChars: 1300,
    supportsNegative: true,
    syntaxHelp: '一句编辑指令即可，如「把背景换成沙滩」「人物穿上图二的衣服」',
  },
  mediaSpec: {
    mode: 'unified_media',
    slots: [
      {
        kind: 'source_image',
        required: true,
        min: 1,
        max: 3,
        accept: ['image'],
        label: '源图片',
        hint: 'JPEG/PNG/WEBP；1-3 张。多图时输出宽高比以最后一张为准',
      },
    ],
  },
  batch: { nativeMax: 6, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 5, max: 20 },
  docPath: 'doc/qwen-image-edit.md',
  description: '基于源图片 + 指令进行编辑/替换/局部修改，支持 1-3 张输入图。',
  parameterSpec: [
    {
      key: 'parameters.size',
      label: '分辨率',
      type: 'enum',
      default: '2048*2048',
      enum: [
        { value: '2048*2048', label: '2048×2048 (1:1)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '2688*1536', label: '2688×1536 (16:9)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1536*2688', label: '1536×2688 (9:16)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '2368*1728', label: '2368×1728 (4:3)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1728*2368', label: '1728×2368 (3:4)', modelScope: ['qwen-image-2.0-pro', 'qwen-image-2.0'] },
        { value: '1664*928', label: '1664×928 (16:9)', modelScope: ['qwen-image-edit-max', 'qwen-image-edit-plus'] },
        { value: '928*1664', label: '928×1664 (9:16)', modelScope: ['qwen-image-edit-max', 'qwen-image-edit-plus'] },
        { value: '1472*1104', label: '1472×1104 (4:3)', modelScope: ['qwen-image-edit-max', 'qwen-image-edit-plus'] },
        { value: '1104*1472', label: '1104×1472 (3:4)', modelScope: ['qwen-image-edit-max', 'qwen-image-edit-plus'] },
        { value: '1328*1328', label: '1328×1328 (1:1)', modelScope: ['qwen-image-edit-max', 'qwen-image-edit-plus'] },
      ],
      dependsOn: [
        { field: 'modelVariant', op: 'in', value: ['qwen-image-2.0-pro', 'qwen-image-2.0', 'qwen-image-edit-max', 'qwen-image-edit-plus'] },
      ],
      sweepable: { allowed: true, strategies: ['list'], costMultiplier: 'linear' },
      help: 'qwen-image-edit 基础版自动推导，不可指定',
    },
    {
      key: 'parameters.n',
      label: '生成张数',
      type: 'int',
      default: 1,
      range: [1, 6],
      step: 1,
      dependsOn: [
        { field: 'modelVariant', op: 'in', value: ['qwen-image-2.0-pro', 'qwen-image-2.0', 'qwen-image-edit-max', 'qwen-image-edit-plus'] },
      ],
      sweepable: { allowed: false },
      help: 'qwen-image-edit 基础版固定为 1',
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      dependsOn: [
        { field: 'modelVariant', op: 'neq', value: 'qwen-image-edit' },
      ],
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
  ],
};

export const wan27VideoEditCapability: Capability = {
  id: 'wan2.7.video_edit',
  displayName: 'Wan 2.7 视频编辑',
  shortName: '视频编辑',
  category: 'v2v',
  providerName: 'dashscope',
  sync: false,
  models: [{ value: 'wan2.7-videoedit', label: 'Wan 2.7 Video Edit', default: true }],
  promptSpec: {
    required: true,
    maxChars: 5000,
    supportsNegative: true,
    syntaxHelp:
      '直接描述修改意图。如「转换为黏土风格」（整体风格变换）或「把女孩的衣服换成参考图中的款式」（局部替换，需配合参考图）',
  },
  mediaSpec: {
    mode: 'unified_media',
    slots: [
      {
        kind: 'source_video',
        required: true,
        min: 1,
        max: 1,
        accept: ['video'],
        label: '源视频',
        hint: 'MP4/MOV，2-10 秒，分辨率 240-4096px，≤100MB',
      },
      {
        kind: 'reference_image',
        required: false,
        min: 0,
        max: 4,
        accept: ['image'],
        label: '参考图 (可选)',
        hint: '局部替换/风格融合时使用；最多 4 张，JPEG/PNG/WEBP，≤20MB',
      },
    ],
  },
  batch: { nativeMax: 1, platformMaxFanout: 500 },
  pollIntervalSec: { initial: 10, max: 30 },
  docPath: 'doc/wan-2.7-video-edit.md',
  description: 'Wan 2.7 视频编辑：风格变换、局部替换、视频重绘。输入 2-10s 视频 + 编辑指令。',
  parameterSpec: [
    {
      key: 'parameters.resolution',
      label: '分辨率',
      type: 'enum',
      default: '1080P',
      enum: [
        { value: '720P', label: '720P' },
        { value: '1080P', label: '1080P' },
      ],
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
      warn: '直接影响计费',
    },
    {
      key: 'parameters.ratio',
      label: '宽高比',
      type: 'enum',
      enum: [
        { value: '16:9', label: '16:9' },
        { value: '9:16', label: '9:16' },
        { value: '1:1', label: '1:1' },
        { value: '4:3', label: '4:3' },
        { value: '3:4', label: '3:4' },
      ],
      sweepable: { allowed: true, strategies: ['list'] },
      help: '不填则跟随输入视频',
    },
    {
      key: 'parameters.duration',
      label: '输出时长 (秒)',
      type: 'int',
      default: 0,
      range: [0, 10],
      step: 1,
      affectsCost: true,
      sweepable: { allowed: true, strategies: ['list'] },
      help: '0 = 跟随输入视频时长；其他值会截断',
    },
    {
      key: 'parameters.audio_setting',
      label: '音频处理',
      type: 'enum',
      default: 'auto',
      enum: [
        { value: 'auto', label: '自动 (智能判断)' },
        { value: 'origin', label: '保留原声' },
      ],
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.prompt_extend',
      label: '智能改写',
      type: 'bool',
      default: true,
      sweepable: { allowed: true, strategies: ['list'] },
    },
    {
      key: 'parameters.watermark',
      label: '添加水印',
      type: 'bool',
      default: false,
      sweepable: { allowed: false },
    },
    {
      key: 'parameters.seed',
      label: 'Seed',
      type: 'int',
      range: [0, 2147483647],
      sweepable: { allowed: true, strategies: ['list', 'randomSeeds'] },
    },
  ],
};

export const ALL_CAPABILITIES: Capability[] = [
  qwenT2ICapability,
  qwenImageEditCapability,
  wan27T2VCapability,
  wan26I2VCapability,
  wan27I2VCapability,
  wan26R2VCapability,
  wan27R2VCapability,
  wan27VideoEditCapability,
];
